routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Jenisruangan;
use App\Paketruangan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    $jnsruangans = Jenisruangan::all();
    $pktruangans = Paketruangan::all();

    return view('welcome')->with(compact('jnsruangans', 'pktruangans'));
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Guesh Order Reservasi
Route::get('/book', 'ReservasiController@reservasi')->name('reservasi');
Route::get('book', 'ReservasiController@book')->name('book');
//Route::get('reservasi/book/page/{page}', 'ReservasiController@bookpage')->name('reservasi.book.page');
Route::post('book/simpan', 'ReservasiController@booksimpan')->name('book.simpan');
Route::get('book/cancel', 'ReservasiController@bookcancel')->name('book.cancel');

// Login First
Route::group(['middleware'=>['auth']], function() {

    Route::get('reservasi/index', 'ReservasiController@index')->name('reservasi.index');
    Route::get('reservasi/filter', 'ReservasiController@filter')->name('reservasi.filter');
    Route::get('reservasi/create', 'ReservasiController@create')->name('reservasi.create');
    Route::get('reservasi/arrived/{id}', 'ReservasiController@arrived')->name('reservasi.arrived');
    Route::post('reservasi', 'ReservasiController@store')->name('reservasi.store');
    Route::get('reservasi/{reservasi}', 'ReservasiController@edit')->name('reservasi.edit');
    Route::put('reservasi/{reservasi}', 'ReservasiController@update')->name('reservasi.update');
    Route::delete('reservasi/{reservasi}', 'ReservasiController@destroy')->name('reservasi.destroy');
    Route::post('reservasi/export', 'ReservasiController@export')->name('reservasi.export');
        
    
    // Only Admin
    Route::group(['middleware'=>['role:admin']], function() {
        Route::resource('jenisruangan', 'JenisruanganController');
        Route::resource('ruangan', 'RuanganController');
        Route::resource('paket', 'PaketController');
                
        //User Management
        Route::resource('user', 'UserController');
        Route::get('user/setpassword/{id}', 'UserController@setpassword')->name('setpassword');
        Route::put('user/updatepassword/{id}', 'UserController@updatepassword')->name('updatepassword');
    });
    
});

    // Checking Session
    Route::get('/check/session', function () {
        return session()->all();
    });

app/Ruangan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Jenisruangan;

class Ruangan extends Model
{
   protected $table = 'ruangan';

    public $primaryKey = 'id_ruangan';

    protected $fillable = [
        'nama_ruangan',
        'nomor',
        'status',
        'id_jenis_ruangan'
    ];

    public function jenisruangan() {
        return Jenisruangan::where('id_jenis_ruangan',$this->id_jenis_ruangan);
    }
}

app/Http/Controllers/RuanganController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Ruangan;
use Session;

class RuanganController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pagetitle = 'Ruangan';
        $ruangan = Ruangan::orderBy('id_ruangan')->paginate(10);

        return view('ruangan.index')->with(compact('pagetitle', 'ruangan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $pagetitle = 'Data Ruangan';
        return view('ruangan.new-ruangan')->with(compact('pagetitle'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_ruangan' => 'required|string|max:30',
            'nomor' => 'required|numeric|unique:ruangan,nomor',
            'status' => 'required|string',
            'id_jenis_ruangan' => 'required',
        ]);

        $ruangan = Ruangan::create($request->all());

        Session::flash('flash_notification', [
            'level' => 'success',
            //'message' => $jenisruangan->nama_jenis_ruangan. 'Berhasil disimpan',
            'message' => $ruangan->nama_ruangan . ' Berhasil disimpan',
        ]);


        return redirect()->route('ruangan.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ruangan = Ruangan::findOrFail($id);
        $pagetitle = 'Data Ruangan';
        return view('ruangan.edit-ruangan')->with(compact('ruangan','pagetitle'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $this->validate($request, [
            'nama_ruangan' => 'required|string|max:30',
            'nomor' => 'required|numeric|unique:ruangan,nomor,'.$id.',id_ruangan',
            'status' => 'required|string',
            'id_jenis_ruangan' => 'required',
        ]);

        $ruangan = Ruangan::findOrFail($id);
        $ruangan->nama_ruangan = $request->get('nama_ruangan');
        $ruangan->nomor = $request->get('nomor');
        $ruangan->status = $request->get('status');
        $ruangan->id_jenis_ruangan = $request->get('id_jenis_ruangan');
        $ruangan->update();

        Session::flash('flash_notification', [
            'level' => 'success',
            //'message' => $jenisruangan->nama_jenis_ruangan. 'Berhasil disimpan',
            'message' => $ruangan->nama_ruangan . ' Berhasil disimpan',
        ]);


        return redirect()->route('ruangan.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $ruangan = Ruangan::findOrFail($id);

        $ruangan->delete();

        Session::flash('flash_notification', [
            'level' => 'warning',
            //'message' => $jenisruangan->nama_jenis_ruangan. 'Berhasil disimpan',
            'message' => $ruangan->nama_ruangan . ' Berhasil dihapus',
        ]);


        return redirect()->route('ruangan.index');
    }
}

resources/views/ruangan/_form-ruangan.blade.php
<div class="form-group {{ $errors->has('id_jenis_ruangan') ? ' has-error' : ''}}">
    {{ Form::label('id_jenis_ruangan', 'Jenis Ruangan', ['class'=>'control-label col-md-4']) }}
    <div class="col-md-4">
        {{ Form::select('id_jenis_ruangan',['' => '== Pilihan ==']+App\Jenisruangan::pluck('nama_jenis_ruangan','id_jenis_ruangan')->all(), null, ['class'=>'form-control']) }}
        {!! $errors->first('id_jenis_ruangan', '<p class="help-block">:message<p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('nama_ruangan') ? ' has-error' : ''}}">
    {{ Form::label('nama_ruangan', 'Nama Ruangan', ['class'=>'control-label col-md-4']) }}
    <div class="col-md-4">
        {{ Form::text('nama_ruangan', null, ['class'=>'form-control']) }}
        {!! $errors->first('nama_ruangan', '<p class="help-block">:message<p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('nomor')? ' has-error' : ''}}">
    {{ Form::label('nomor', 'Nomor Ruangan', ['class'=>'control-label col-md-4']) }}
    <div class="col-md-4">
        {{ Form::text('nomor', null, ['class'=>'form-control', 'data-mask'])}}
        {!! $errors->first('nomor', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('status') ? ' has-error' : ''}}">
    {{ Form::label('status', 'Status', ['class'=>'control-label col-md-4']) }}
    <div class="col-md-4">
        {{ Form::select('status',['' => '== Pilihan ==', 'close' => 'Tutup','open' => 'Buka'], null, ['class'=>'form-control']) }}
        {!! $errors->first('status', '<p class="help-block">:message<p>') !!}
    </div>
</div>

resources/views/ruangan/_import-kelurahan.blade.php
<div class="row">
    <div class="form-group row col-md-6">
        {{ Form::label('', 'Gunakan Template Import Excel', ['class'=>'col-form-label col-md-4']) }}
        <div class="col-md-8">
            <a href="{{ route('kelurahan.generate.template') }}" class="btn btn-info">Download</a>
        </div>
    </div>
</div>
<div class="row">
    <div class="form-group row col-md-6">
        {{ Form::label('excel', 'Pilih File', ['class'=>'col-form-label col-md-4']) }}
        <div class="col-md-8">
        {{ Form::file('excel') }}
        {{ $errors->has('excel') ? $errors->first('excel'): ''}}
        </div>
    </div>
</div>

resources/views/ruangan/bkp_index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex p-0">
                    <div class="card-title p-3">Daftar Kecamatan</div>
                    <ul class="nav nav-pills ml-auto p-2">
                        <li class="nav-item"><a class="nav-link active" href="{{route('kecamatan.create')}}">Tambah Kecamatan</a></li>
                    </ul>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Nama Kecamatan</th>
                                    <th>Kode Kecamatan</th>
                                    <th>Luas Wilayah</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if(isset($kec) && $kec->count() > 0)
                                <?php $i = $kec->FirstItem(); ?>
                                @foreach($kec as $kc)
                                    <tr>
                                        <td>{{ $i }}</td>
                                        <td>{{ $kc->nama }}</td>
                                        <td>{{ $kc->kode }}</td>
                                        <td>{{ $kc->luas }}</td>
                                        <td>
                                            <a href="{{ route('kecamatan.edit', $kc->id) }}"class="btn-info btn-sm">Edit</a>
                                            <a href="{{ route('kecamatan.destroy', $kc->id) }}"class="btn-danger btn-sm" onclick="event.preventDefault();document.getElementById('formdelete{{ $kc->id }}').submit()">Hapus</a>
                                            {{ Form::open(['url'=>route('kecamatan.destroy', $kc->id), 'method'=>'delete', 'style'=>'display:none;', 'id'=>'formdelete'.$kc->id])}}
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                    <?php $i++; ?>
                                @endforeach
                                @else
                                    <tr><td colspan="5"> Data Kosong </td></tr>
                                @endif
                            </body>
                        </table>
                    </div>
                    <div class="float-left pagination-md mb-0 clear-fix">
                            Menampilkan {{ $kec->FirstItem() }} sampai {{$kec->LastItem()}} Dari {{$kec->total()}} Entri
                    </div>
                    <div class="float-right pagination-md mb-0 clear-fix">
                            {{$kec->links()}}
                    </div>
                </div>
                <div class="overlay preload">
                    <i class="fa fa-refresh fa-spin"></i>
                </div>
            </div>
        </div>

        <div class="card-body">
                <div class="d-flex">
                  <p class="d-flex flex-column">
                    <span class="text-bold text-lg">$18,230.00</span>
                    <span>Sales Over Time</span>
                  </p>
                  <p class="ml-auto d-flex flex-column text-right">
                    <span class="text-success">
                      <i class="fa fa-arrow-up"></i> 33.1%
                    </span>
                    <span class="text-muted">Since last month</span>
                  </p>
                </div>
                <!-- /.d-flex -->

                <div class="position-relative mb-4">
                  <canvas id="sales-chart" height="200"></canvas>
                </div>

                <div class="d-flex flex-row justify-content-end">
                  <span class="mr-2">
                    <i class="fa fa-square text-primary"></i> This year
                  </span>

                  <span>
                    <i class="fa fa-square text-gray"></i> Last year
                  </span>
                </div>
              </div>
            </div>
        </div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function () {
            $('.preload').fadeOut();
        });
    </script>
@endsection

resources/views/ruangan/edit-ruangan.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
               <div class="card card-info">
                   <div class="card-header">
                        <h3 class="card-title">Edit Ruangan {{ $ruangan->nama}}</h3>
                   </div>
                   <div class="card-body">
                        {!! Form::model($ruangan,['url'=> route('ruangan.update', $ruangan->id_ruangan),'class'=>'form-horizontal','method'=>'put', 'files'=>'true'])!!}
                            @include('ruangan._form-ruangan')
                            
                            <div class="col-md-4 col-md-offset-4">
                                {{ Form::submit('Simpan', ['class'=>'btn btn-primary'])}}
                                <a href="{{ route('ruangan.index') }}" class="btn btn-info">Kembali</a>
                            </div>
                        {!! Form::close()!!}
                   </div>
               </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="http://localhost:8000/adminlte/plugins/input-mask/jquery.inputmask.js"></script>
    <script>
        $(document).ready(function() {
            $('[data-mask]').inputmask('9999');
        });
    </script>
@endsection

resources/views/ruangan/import-kelurahan.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
               <div class="card card-info">
                   <div class="card-header">
                        <a href="{{ route('kelurahan.index') }}">Data Kelurahan </a> > Import Kelurahan
                   </div>
                   <div class="card-body">
                        {!! Form::open(['url'=> route('kelurahan.importpost.excel'),'class'=>'form-horizontal', 'metode'=>'post','files'=>'true','enctype'=>'multipart/form-data'])!!}
                                @include('kelurahan._import-kelurahan')
                                <div class="offset-md-2">
                                    {{ Form::submit('Import', ['class'=>'btn btn-primary'])}}
                                    <a href="{{ route('kelurahan.index') }}" class="btn btn-info">Kembali</a>
                                </div>
                            </div>
                        {!! Form::close()!!}
                   </div>
               </div>
            </div>
        </div>
    </div>
@endsection


@section('scripts')
    <script src="http://localhost:8000/adminlte/plugins/input-mask/jquery.inputmask.js"></script>
    <script>
        $(document).ready(function() {
            $('[data-mask]').inputmask('9999');
        });
        $(function() {
            $('.tandawarna').colorpicker();
        });
    </script>
@endsection

resources/views/ruangan/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-info">
                <div class="card-header d-flex p-0">
                    <h3 class="card-title p-3">Daftar Ruangan</h3>
                    <ul class="nav nav-pills ml-auto p-2">
                        <li class="nav-item"><a class="nav-link" href="{{route('ruangan.create')}}"><i class="fa fa-plus"></i> Tambah Ruangan</a></li>
                        <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" >
                                    <i class="fa fa-bars"></i>
                                </a>
                                <div class="dropdown-menu">
                                    <!--a class="dropdown-item" tabindex="-1" href="#" style="color:black">
                                        <i class="fa fa-refresh fa-spin"></i>
                                        Action
                                        <span class="float-right text-muted text-sm"></span>
                                    </a-->
                                    <div class="divider"></div>
                                    <!--a class="dropdown-item" tabindex="-1" href="route('kelurahan.import.excel')"-->
                                    <a class="dropdown-item" tabindex="-1" href="#">
                                        <i class="fa fa-upload" style="color:black;"></i>
                                        <span style="color:black">Impor dari Excel</span>
                                        <span class="float-right text-muted text-sm"></span>
                                    </a>
                                    <!--a class="dropdown-item" tabindex="-1" href="route('kelurahan.export.excel')"-->
                                    <a class="dropdown-item" tabindex="-1" href="#">
                                        <i class="fa fa-file" style="color:black;"></i>
                                        <span style="color:black">Ekspor Data Kelurahan ke Excel</span>
                                        <span class="float-right text-muted text-sm"></span>
                                    </a>
                                </div>
                        </li> 
                    </ul>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Nomor Ruangan</th>
                                    <th>Nama Ruangan</th>
                                    <th>Jenis Ruangan</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if(isset($ruangan) && $ruangan->count() > 0)
                                <?php $i = $ruangan->FirstItem(); ?>
                                @foreach($ruangan as $ruang)
                                    <tr>
                                        <td>{{ $i }}</td>
                                        <td>{{ $ruang->nomor }}</td>
                                        <td>{{ $ruang->nama_ruangan }}</td>
                                        <td>{{ App\Jenisruangan::find($ruang->id_jenis_ruangan)->nama_jenis_ruangan }}</td>
                                        <td>{{ $ruang->status }}</td>
                                        <td>
                                            <a href="{{ route('ruangan.edit', $ruang->id_ruangan) }}"class="btn-info btn-sm">Edit</a>
                                            <a href="#" class="btn-danger btn-sm" onclick=" var check = confirm('Yakin Hapus {{ $ruang->nama_ruangan }}?'); if(check) {event.preventDefault();document.getElementById('formdelete{{ $ruang->id_ruangan }}').submit();}" >Hapus</a>
                                            {{ Form::open(['url'=>route('ruangan.destroy', $ruang->id_ruangan), 'method'=>'delete', 'id'=>'formdelete'.$ruang->id_ruangan, 'class'=>'form-inline', 'data-confirm'=>'Yakin Hapus '.$ruang->nama_ruangan])}}
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                    <?php $i++; ?>
                                @endforeach
                                @else
                                    <tr><td colspan="6" class="text-center"> Data Kosong </td></tr>
                                @endif
                            </body>
                        </table>
                    </div>
                    <div class="float-left pagination-md mb-0 clear-fix">
                          @if(isset($ruangan) && $ruangan->count() > 0)
                            Menampilkan {{ $ruangan->FirstItem() }} sampai {{$ruangan->LastItem()}} Dari {{$ruangan->total()}} Entri
                          @endif
                    </div>
                    <div class="float-right pagination-md mb-0 clear-fix">
                          @if(isset($ruangan) && $ruangan->count() > 0)
                            {{$ruangan->links()}}
                          @endif
                    </div>
                </div>
                <!--div class="overlay preload">
                    <i class="fa fa-refresh fa-spin"></i>
                </div-->
            </div>
        </div>

        <!--div class="card col-md-4">
            <div class="card-body">
                <div class="d-flex">
                  <p class="d-flex flex-column">
                    <span class="text-bold text-lg">$18,230.00</span>
                    <span>Sales Over Time</span>
                  </p>
                  <p class="ml-auto d-flex flex-column text-right">
                    <span class="text-success">
                      <i class="fa fa-arrow-up"></i> 33.1%
                    </span>
                    <span class="text-muted">Since last month</span>
                  </p>
                </div>


                <div class="position-relative mb-4">
                  <canvas id="sales-chart" height="200"></canvas>
                </div>

                <div class="d-flex flex-row justify-content-end">
                  <span class="mr-2">
                    <i class="fa fa-square text-primary"></i> This year
                  </span>

                  <span>
                    <i class="fa fa-square text-gray"></i> Last year
                  </span>
                </div>
            </div>
        </div-->

    </div>
        <!-- iframe class="container-fluid" height="800px" src="{{url('print/pdf')}}"></iframe-->
</div>

@endsection

@section('scripts')
    <script>
        $(document).ready(function () {
            $('.preload').fadeOut();
        });
    </script>
@endsection

resources/views/ruangan/new-ruangan.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
               <div class="card card-info">
                   <div class="card-header">
                        <h3 class="card-title">Form New Ruangan</h3>
                   </div>
                   <div class="card-body">
                        {!! Form::open(['url'=> route('ruangan.store'),'method'=>'post', 'files'=>'true','class'=>'form-horizontal'])!!}
                            @include('ruangan._form-ruangan')
                            <div class="col-md-4">
                                {{ Form::submit('Simpan', ['class'=>'btn btn-primary'])}}
                                <a href="{{ route('jenisruangan.index') }}" class="btn btn-info">Kembali</a>
                            </div>
                        {!! Form::close()!!}
                   </div>
               </div>
            </div>
        </div>
    </div>
@endsection


@section('scripts')
    <script src="http://localhost:8000/adminlte/plugins/input-mask/jquery.inputmask.js"></script>
    <script>
        $(document).ready(function() {
            $('[data-mask]').inputmask('9999');
        });
    </script>
@endsection