routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Jenisruangan;
use App\Paketruangan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    $jnsruangans = Jenisruangan::all();
    $pktruangans = Paketruangan::all();

    return view('welcome')->with(compact('jnsruangans', 'pktruangans'));
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Guesh Order Reservasi
Route::get('/book', 'ReservasiController@reservasi')->name('reservasi');
Route::get('book', 'ReservasiController@book')->name('book');
//Route::get('reservasi/book/page/{page}', 'ReservasiController@bookpage')->name('reservasi.book.page');
Route::post('book/simpan', 'ReservasiController@booksimpan')->name('book.simpan');
Route::get('book/cancel', 'ReservasiController@bookcancel')->name('book.cancel');

// Login First
Route::group(['middleware'=>['auth']], function() {

    Route::get('reservasi/index', 'ReservasiController@index')->name('reservasi.index');
    Route::get('reservasi/filter', 'ReservasiController@filter')->name('reservasi.filter');
    Route::get('reservasi/create', 'ReservasiController@create')->name('reservasi.create');
    Route::get('reservasi/arrived/{id}', 'ReservasiController@arrived')->name('reservasi.arrived');
    Route::post('reservasi', 'ReservasiController@store')->name('reservasi.store');
    Route::get('reservasi/{reservasi}', 'ReservasiController@edit')->name('reservasi.edit');
    Route::put('reservasi/{reservasi}', 'ReservasiController@update')->name('reservasi.update');
    Route::delete('reservasi/{reservasi}', 'ReservasiController@destroy')->name('reservasi.destroy');
    Route::post('reservasi/export', 'ReservasiController@export')->name('reservasi.export');
        
    
    // Only Admin
    Route::group(['middleware'=>['role:admin']], function() {
        Route::resource('jenisruangan', 'JenisruanganController');
        Route::resource('ruangan', 'RuanganController');
        Route::resource('paket', 'PaketController');
                
        //User Management
        Route::resource('user', 'UserController');
        Route::get('user/setpassword/{id}', 'UserController@setpassword')->name('setpassword');
        Route::put('user/updatepassword/{id}', 'UserController@updatepassword')->name('updatepassword');
    });
    
});

    // Checking Session
    Route::get('/check/session', function () {
        return session()->all();
    });

app/Jenisruangan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Ruangan;

class Jenisruangan extends Model
{
    protected $table = 'jenis_ruangan';

    public $primaryKey = 'id_jenis_ruangan';

    protected $fillable = [
        'nama_jenis_ruangan',
        'harga',
        'foto',
        'keterangan'
    ];

    public function ruangan() {
        return Ruangan::where('id_jenis_ruangan', $this->id_jenis_ruangan);
    }
}

app/Http/Controllers/JenisruanganController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Jenisruangan;
use Session;
use Illuminate\Support\Facades\File; 

class JenisruanganController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $pagetitle = 'Jenis Ruangan';
        $jenisruangan = Jenisruangan::orderBy('id_jenis_ruangan')->paginate(10);

        return view('jenisruangan.index')->with(compact('pagetitle', 'jenisruangan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $pagetitle = 'Jenis Ruangan';
        return view('jenisruangan.new-jenisruangan')->with(compact('pagetitle'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_jenis_ruangan' => 'required|string|max:30|unique:jenis_ruangan,nama_jenis_ruangan',
            'harga' => 'required|numeric',
	        'foto' => 'required|max:2048',
	        'keterangan' => 'required|string',
        ]);

        $jenisruangan = Jenisruangan::create($request->except('foto'));

        if($request->hasFile('foto')) {
            $uploadfoto = $request->file('foto');

            //ambil extension file
            $extension = $uploadfoto->getClientOriginalExtension();

            //membuat nama file
            $namefile = md5(time()). '.' . $extension;

            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'img';

            $uploadfoto->move($destinationPath, $namefile);

            $jenisruangan->foto = $namefile;

            $jenisruangan->save();
        }

        Session::flash('flash_notification', [
            'level' => 'success',
            //'message' => $jenisruangan->nama_jenis_ruangan. 'Berhasil disimpan',
            'message' => $jenisruangan->nama_jenis_ruangan . ' Berhasil disimpan',
        ]);


        return redirect()->route('jenisruangan.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $jenisruangan = Jenisruangan::findOrFail($id);

        return view('jenisruangan.edit-jenisruangan')->with(compact('jenisruangan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nama_jenis_ruangan' => 'required|string|max:30|unique:jenis_ruangan,nama_jenis_ruangan,'.$id.',id_jenis_ruangan',
            'harga' => 'required|numeric',
	        'keterangan' => 'required|string',
        ]);

        $jenisruangan = Jenisruangan::find($id);
        $jenisruangan->update($request->except('foto'));

        if($request->hasFile('foto')) {
            $namefile = null;
            $uploadfoto = $request->file('foto');

            //ambil extension file
            $extension = $uploadfoto->getClientOriginalExtension();

            //membuat nama file
            $namefile = md5(time()). '.' . $extension;

            $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'img';

            $uploadfoto->move($destinationPath, $namefile);

            //menghapus file lama jika ada
            if($jenisruangan->foto) {
                $old_foto = $jenisruangan->foto;

                $filepath = public_path() . DIRECTORY_SEPARATOR . 'img' . DIRECTORY_SEPARATOR . $jenisruangan->foto;

                try {
                    File::delete($filepath);
                } catch(FileNotFoundException $e) {
                    // File sudah di hapus/tidak ada
                }
            }

            //ganti file baru
            $jenisruangan->foto = $namefile;

            $jenisruangan->update();
        }

        Session::flash('flash_notification', [
            'level' => 'success',
            //'message' => $jenisruangan->nama_jenis_ruangan. 'Berhasil disimpan',
            'message' => $jenisruangan->nama_jenis_ruangan . 'Berhasil disimpan',
        ]);


        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $jenisruangan = Jenisruangan::findOrFail($id);

        if($jenisruangan->foto) {

            $old_foto = $jenisruangan->foto;

            $filepath = public_path() . DIRECTORY_SEPARATOR . 'img' . DIRECTORY_SEPARATOR . $jenisruangan->foto;

            try {
                File::delete($filepath);
            } catch(FileNotFoundException $e) {
                // File sudah di hapus/tidak ada
            }
        }

        $jenisruangan->delete();

        Session::flash('flash_notification', [
            'level' => 'success',
            'message' => $jenisruangan->nama_jenis_ruangan. 'Berhasil dihapus',
        ]);


        return redirect()->route('jenisruangan.index');
    }
}

resources/views/jenisruangan/_form-jenisruangan.blade.php
<div class="form-group {{ $errors->has('nama_jenis_ruangan') ? ' has-error' : ''}}">
    {{ Form::label('nama_jenis_ruangan', 'Nama', ['class'=>'control-label col-md-4']) }}
    <div class="col-md-4">
        {{ Form::text('nama_jenis_ruangan', null, ['class'=>'form-control']) }}
        {!! $errors->first('nama_jenis_ruangan', '<p class="help-block">:message<p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('harga')? ' has-error' : ''}}">
    {{ Form::label('harga', 'Harga', ['class'=>'control-label col-md-4']) }}
    <div class="col-md-4">
        {{ Form::text('harga', null, ['class'=>'form-control', 'data-mask'])}}
        {!! $errors->first('harga', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('foto')? ' has-error' : ''}}">
    {{ Form::label('foto', 'Image', ['class'=>'control-label col-md-4']) }}
    <div class="col-md-4">
        {{ Form::file('foto',['class'=>''])}}
        {!! $errors->first('foto', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group">
    @if(isset($jenisruangan) && $jenisruangan->foto)
        <image src="{{ asset('img/'.$jenisruangan->foto) }}" class="img-rounded img-fluid"/>
    @endif
</div>
<div class="form-group {{ $errors->has('keterangan')? ' has-error' : ''}}">
    {{ Form::label('keterangan', 'Keterangan', ['class'=>'control-label col-md-4']) }}
    <div class="col-md-4">
        {{ Form::text('keterangan', null, ['class'=>'form-control'])}}
        {!! $errors->first('keterangan', '<p class="help-block">:message<p>') !!}
    </div>
</div>

resources/views/jenisruangan/_import-kelurahan.blade.php
<div class="row">
    <div class="form-group row col-md-6">
        {{ Form::label('', 'Gunakan Template Import Excel', ['class'=>'col-form-label col-md-4']) }}
        <div class="col-md-8">
            <a href="{{ route('kelurahan.generate.template') }}" class="btn btn-info">Download</a>
        </div>
    </div>
</div>
<div class="row">
    <div class="form-group row col-md-6">
        {{ Form::label('excel', 'Pilih File', ['class'=>'col-form-label col-md-4']) }}
        <div class="col-md-8">
        {{ Form::file('excel') }}
        {{ $errors->has('excel') ? $errors->first('excel'): ''}}
        </div>
    </div>
</div>

resources/views/jenisruangan/bkp_index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex p-0">
                    <div class="card-title p-3">Daftar Kecamatan</div>
                    <ul class="nav nav-pills ml-auto p-2">
                        <li class="nav-item"><a class="nav-link active" href="{{route('kecamatan.create')}}">Tambah Kecamatan</a></li>
                    </ul>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Nama Kecamatan</th>
                                    <th>Kode Kecamatan</th>
                                    <th>Luas Wilayah</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if(isset($kec) && $kec->count() > 0)
                                <?php $i = $kec->FirstItem(); ?>
                                @foreach($kec as $kc)
                                    <tr>
                                        <td>{{ $i }}</td>
                                        <td>{{ $kc->nama }}</td>
                                        <td>{{ $kc->kode }}</td>
                                        <td>{{ $kc->luas }}</td>
                                        <td>
                                            <a href="{{ route('kecamatan.edit', $kc->id) }}"class="btn-info btn-sm">Edit</a>
                                            <a href="{{ route('kecamatan.destroy', $kc->id) }}"class="btn-danger btn-sm" onclick="event.preventDefault();document.getElementById('formdelete{{ $kc->id }}').submit()">Hapus</a>
                                            {{ Form::open(['url'=>route('kecamatan.destroy', $kc->id), 'method'=>'delete', 'style'=>'display:none;', 'id'=>'formdelete'.$kc->id])}}
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                    <?php $i++; ?>
                                @endforeach
                                @else
                                    <tr><td colspan="5"> Data Kosong </td></tr>
                                @endif
                            </body>
                        </table>
                    </div>
                    <div class="float-left pagination-md mb-0 clear-fix">
                            Menampilkan {{ $kec->FirstItem() }} sampai {{$kec->LastItem()}} Dari {{$kec->total()}} Entri
                    </div>
                    <div class="float-right pagination-md mb-0 clear-fix">
                            {{$kec->links()}}
                    </div>
                </div>
                <div class="overlay preload">
                    <i class="fa fa-refresh fa-spin"></i>
                </div>
            </div>
        </div>

        <div class="card-body">
                <div class="d-flex">
                  <p class="d-flex flex-column">
                    <span class="text-bold text-lg">$18,230.00</span>
                    <span>Sales Over Time</span>
                  </p>
                  <p class="ml-auto d-flex flex-column text-right">
                    <span class="text-success">
                      <i class="fa fa-arrow-up"></i> 33.1%
                    </span>
                    <span class="text-muted">Since last month</span>
                  </p>
                </div>
                <!-- /.d-flex -->

                <div class="position-relative mb-4">
                  <canvas id="sales-chart" height="200"></canvas>
                </div>

                <div class="d-flex flex-row justify-content-end">
                  <span class="mr-2">
                    <i class="fa fa-square text-primary"></i> This year
                  </span>

                  <span>
                    <i class="fa fa-square text-gray"></i> Last year
                  </span>
                </div>
              </div>
            </div>
        </div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function () {
            $('.preload').fadeOut();
        });
    </script>
@endsection

resources/views/jenisruangan/edit-jenisruangan.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
               <div class="card card-info">
                   <div class="card-header">
                        <h3 class="card-title">Edit Jenis Ruangan {{ $jenisruangan->nama}}</h3>
                   </div>
                   <div class="card-body">
                        {!! Form::model($jenisruangan,['url'=> route('jenisruangan.update', $jenisruangan->id_jenis_ruangan),'class'=>'form-horizontal','method'=>'put', 'files'=>'true'])!!}
                            @include('jenisruangan._form-jenisruangan')
                            
                            <div class="col-md-4 col-md-offset-4">
                                {{ Form::submit('Simpan', ['class'=>'btn btn-primary'])}}
                                <a href="{{ route('jenisruangan.index') }}" class="btn btn-info">Kembali</a>
                            </div>
                        {!! Form::close()!!}
                   </div>
               </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="http://localhost:8000/adminlte/plugins/input-mask/jquery.inputmask.js"></script>
    <script>
        $(document).ready(function() {
            $('[data-mask]').inputmask('9999');
        });
    </script>
@endsection

resources/views/jenisruangan/import-kelurahan.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
               <div class="card card-info">
                   <div class="card-header">
                        <a href="{{ route('kelurahan.index') }}">Data Kelurahan </a> > Import Kelurahan
                   </div>
                   <div class="card-body">
                        {!! Form::open(['url'=> route('kelurahan.importpost.excel'),'class'=>'form-horizontal', 'metode'=>'post','files'=>'true','enctype'=>'multipart/form-data'])!!}
                                @include('kelurahan._import-kelurahan')
                                <div class="offset-md-2">
                                    {{ Form::submit('Import', ['class'=>'btn btn-primary'])}}
                                    <a href="{{ route('kelurahan.index') }}" class="btn btn-info">Kembali</a>
                                </div>
                            </div>
                        {!! Form::close()!!}
                   </div>
               </div>
            </div>
        </div>
    </div>
@endsection


@section('scripts')
    <script src="http://localhost:8000/adminlte/plugins/input-mask/jquery.inputmask.js"></script>
    <script>
        $(document).ready(function() {
            $('[data-mask]').inputmask('9999');
        });
        $(function() {
            $('.tandawarna').colorpicker();
        });
    </script>
@endsection

resources/views/jenisruangan/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-info">
                <div class="card-header d-flex p-0">
                    <h3 class="card-title p-3">Daftar Jenis Ruangan</h3>
                    <ul class="nav nav-pills ml-auto p-2">
                        <li class="nav-item"><a class="nav-link" href="{{route('jenisruangan.create')}}"><i class="fa fa-plus"></i> Tambah Jenis Ruangan</a></li>
                        <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" >
                                    <i class="fa fa-bars"></i>
                                </a>
                                <div class="dropdown-menu">
                                    <!--a class="dropdown-item" tabindex="-1" href="#" style="color:black">
                                        <i class="fa fa-refresh fa-spin"></i>
                                        Action
                                        <span class="float-right text-muted text-sm"></span>
                                    </a-->
                                    <div class="divider"></div>
                                    <!--a class="dropdown-item" tabindex="-1" href="route('kelurahan.import.excel')"-->
                                    <a class="dropdown-item" tabindex="-1" href="#">
                                        <i class="fa fa-upload" style="color:black;"></i>
                                        <span style="color:black">Impor dari Excel</span>
                                        <span class="float-right text-muted text-sm"></span>
                                    </a>
                                    <!--a class="dropdown-item" tabindex="-1" href="route('kelurahan.export.excel')"-->
                                    <a class="dropdown-item" tabindex="-1" href="#">
                                        <i class="fa fa-file" style="color:black;"></i>
                                        <span style="color:black">Ekspor Data Kelurahan ke Excel</span>
                                        <span class="float-right text-muted text-sm"></span>
                                    </a>
                                </div>
                        </li> 
                    </ul>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Nama Ruangan</th>
                                    <th>Harga</th>
                                    <th>Foto</th>
                                    <th>Keterangan</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if(isset($jenisruangan) && $jenisruangan->count() > 0)
                                <?php $i = $jenisruangan->FirstItem(); $datesss = 'test'; ?>
                                @foreach($jenisruangan as $jnsruang)
                                    <tr>
                                        <td>{{ $i }}</td>
                                        <td>{{ $jnsruang->nama_jenis_ruangan }}</td>
                                        <td>{{ $jnsruang->harga }}</td>
                                        <td>{{ $jnsruang->foto }}</td>
                                        <td>{{ $jnsruang->keterangan }}</td>
                                        <td>
                                            <a href="{{ route('jenisruangan.edit', $jnsruang->id_jenis_ruangan) }}"class="btn-info btn-sm">Edit</a>
                                            <a href="#" class="btn-danger btn-sm" onclick=" var check = confirm('Yakin Hapus {{ $jnsruang->nama_jenis_ruangan }}?'); if(check) {event.preventDefault();document.getElementById('formdelete{{ $jnsruang->id_jenis_ruangan }}').submit();}" >Hapus</a>
                                            {{ Form::open(['url'=>route('jenisruangan.destroy', $jnsruang->id_jenis_ruangan), 'method'=>'delete', 'id'=>'formdelete'.$jnsruang->id_jenis_ruangan, 'class'=>'form-inline', 'data-confirm'=>'Yakin Hapus '.$jnsruang->nama_jenis_ruangan])}}
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                    <?php $i++; ?>
                                @endforeach
                                @else
                                    <tr><td colspan="6" class="text-center"> Data Kosong </td></tr>
                                @endif
                            </body>
                        </table>
                    </div>
                    <div class="float-left pagination-md mb-0 clear-fix">
                          @if(isset($jenisruangan) && $jenisruangan->count() > 0)
                            Menampilkan {{ $jenisruangan->FirstItem() }} sampai {{$jenisruangan->LastItem()}} Dari {{$jenisruangan->total()}} Entri
                          @endif
                    </div>
                    <div class="float-right pagination-md mb-0 clear-fix">
                          @if(isset($jenisruangan) && $jenisruangan->count() > 0)
                            {{$jenisruangan->links()}}
                          @endif
                    </div>
                </div>
                <!--div class="overlay preload">
                    <i class="fa fa-refresh fa-spin"></i>
                </div-->
            </div>
        </div>

        <!--div class="card col-md-4">
            <div class="card-body">
                <div class="d-flex">
                  <p class="d-flex flex-column">
                    <span class="text-bold text-lg">$18,230.00</span>
                    <span>Sales Over Time</span>
                  </p>
                  <p class="ml-auto d-flex flex-column text-right">
                    <span class="text-success">
                      <i class="fa fa-arrow-up"></i> 33.1%
                    </span>
                    <span class="text-muted">Since last month</span>
                  </p>
                </div>


                <div class="position-relative mb-4">
                  <canvas id="sales-chart" height="200"></canvas>
                </div>

                <div class="d-flex flex-row justify-content-end">
                  <span class="mr-2">
                    <i class="fa fa-square text-primary"></i> This year
                  </span>

                  <span>
                    <i class="fa fa-square text-gray"></i> Last year
                  </span>
                </div>
            </div>
        </div-->

    </div>
        <!-- iframe class="container-fluid" height="800px" src="{{url('print/pdf')}}"></iframe-->
</div>

@endsection

@section('scripts')
    <script>
        $(document).ready(function () {
            $('.preload').fadeOut();
        });
    </script>
@endsection

resources/views/jenisruangan/new-jenisruangan.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
               <div class="card card-info">
                   <div class="card-header">
                        <h3 class="card-title">Form New Jenis Ruangan</h3>
                   </div>
                   <div class="card-body">
                        {!! Form::open(['url'=> route('jenisruangan.store'),'method'=>'post', 'files'=>'true','class'=>'form-horizontal'])!!}
                            @include('jenisruangan._form-jenisruangan')
                            <div class="col-md-4">
                                {{ Form::submit('Simpan', ['class'=>'btn btn-primary'])}}
                                <a href="{{ route('jenisruangan.index') }}" class="btn btn-info">Kembali</a>
                            </div>
                        {!! Form::close()!!}
                   </div>
               </div>
            </div>
        </div>
    </div>
@endsection


@section('scripts')
    <script src="http://localhost:8000/adminlte/plugins/input-mask/jquery.inputmask.js"></script>
    <script>
        $(document).ready(function() {
            $('[data-mask]').inputmask('9999');
        });
    </script>
@endsection