routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Jenisruangan;
use App\Paketruangan;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    $jnsruangans = Jenisruangan::all();
    $pktruangans = Paketruangan::all();

    return view('welcome')->with(compact('jnsruangans', 'pktruangans'));
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Guesh Order Reservasi
Route::get('/book', 'ReservasiController@reservasi')->name('reservasi');
Route::get('book', 'ReservasiController@book')->name('book');
//Route::get('reservasi/book/page/{page}', 'ReservasiController@bookpage')->name('reservasi.book.page');
Route::post('book/simpan', 'ReservasiController@booksimpan')->name('book.simpan');
Route::get('book/cancel', 'ReservasiController@bookcancel')->name('book.cancel');

// Login First
Route::group(['middleware'=>['auth']], function() {

    Route::get('reservasi/index', 'ReservasiController@index')->name('reservasi.index');
    Route::get('reservasi/filter', 'ReservasiController@filter')->name('reservasi.filter');
    Route::get('reservasi/create', 'ReservasiController@create')->name('reservasi.create');
    Route::get('reservasi/arrived/{id}', 'ReservasiController@arrived')->name('reservasi.arrived');
    Route::post('reservasi', 'ReservasiController@store')->name('reservasi.store');
    Route::get('reservasi/{reservasi}', 'ReservasiController@edit')->name('reservasi.edit');
    Route::put('reservasi/{reservasi}', 'ReservasiController@update')->name('reservasi.update');
    Route::delete('reservasi/{reservasi}', 'ReservasiController@destroy')->name('reservasi.destroy');
    Route::post('reservasi/export', 'ReservasiController@export')->name('reservasi.export');
        
    
    // Only Admin
    Route::group(['middleware'=>['role:admin']], function() {
        Route::resource('jenisruangan', 'JenisruanganController');
        Route::resource('ruangan', 'RuanganController');
        Route::resource('paket', 'PaketController');
                
        //User Management
        Route::resource('user', 'UserController');
        Route::get('user/setpassword/{id}', 'UserController@setpassword')->name('setpassword');
        Route::put('user/updatepassword/{id}', 'UserController@updatepassword')->name('updatepassword');
    });
    
});

    // Checking Session
    Route::get('/check/session', function () {
        return session()->all();
    });

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Role;
use Session;
use Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        //$user = User::where('id','!=', $user->id)->paginate(5); //tidak menampilkan Admin yang aktif
        $user = User::orderBy('id')->paginate(5); //menampilkan semua user
        //for view
        $pagetitle = 'Manage Accounts';
        return view('user.index')->with(compact('user','pagetitle'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::pluck('name','id')->all();
        //return $role;
        //for view
        $pagetitle = 'Manage Accounts';
        return view('user.new-user')->with(compact('roles', 'pagetitle'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string',
            'username' => 'required|string|unique:users',
            'email' => 'required|string|unique:users', //tambah email untuk reset password
            'password' => 'required|string|min:8|confirmed',
            'role' => 'required'
        ]);

        $user = new User();
        $user->name = $request->get('name');
        $user->username = $request->get('username');
        $user->email = $request->get("email");
        $user->password = bcrypt($request->get('password'));
        $user->save();

        $user->roles()->sync([$request->get('role')]);

        Session::flash('flash_notification', [
            'level' => 'success',
            'message' => $user->name .' berhasil disimpan',
        ]);

        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //for data
        $roles = Role::pluck('name', 'id')->all();
        $user = User::find($id);
        $role = $user->roles->first()->id;
        
        return view('user.show-user')->with(compact('user', 'roles','role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //for data
        $roles = Role::pluck('name','id')->all();
        $user = User::find($id);
        $role = $user->roles->first()->id;

        $pagetitle = 'Manage Accounts';
        return view('user.edit-user')->with(compact('user','roles', 'role', 'pagetitle'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
           'name' => 'required|string|unique:users,name,'.$id,
           'email' => 'required|string|unique:users,email,'.$id,
           'role' => 'required|exists:roles,id'
        ]);

        $user = User::find($id);
        $user->name = $request->get('name');
        $user->email = $request->get('email');
        $user->save();

        $user->roles()->sync([$request->get('role')]);
        
        Session::flash('flash_notification', [
            'level' => 'success',
            'message' => $user->name.' Berhasil diperbarui',
        ]);

        //return redirect()->route('user.index');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $usr = User::findOrFail($id);

        //hapus akun
        $usr->delete();

        //notifikasi
        Session::flash('flash_notification', [
            'level' => 'info',
            'message' => $usr->name.' Berhasil dihapus',
        ]);

        //kembali ke halaman
        return redirect()->route('user.index');
    }

    public function setpassword($id)
    {
        //for data
        $roles = Role::pluck('name','id')->all();
        $user = User::find($id);
        $role = $user->roles->first()->id;

        return view('user.set-password')->with(compact('user','roles', 'role'));
    }

    public function updatepassword(Request $request, $id) {
        $this->validate($request, [
            'password' => 'required|string|min:5|confirmed',
        ]);

        $user = User::findOrFail($id);
        $user->password = bcrypt($request->get('password'));
        $user->save();

        Session::flash('flash_notification', [
            'level' => 'success',
            'message' => 'Password berhasil diganti',
        ]);

        return redirect()->route('user.index');
    }
}

resources/views/user/_form-edit-user.blade.php
<div class="form-group row{{ $errors->has('name') ? ' has-error': ''}}">
    {!! Form::label('name', 'Nama', ['class'=>'text-md-right col-form-label col-md-4'])!!}
    <div class="col-md-4">
        {!! Form::text('name', null, ['class'=>'form-control']) !!}
        {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group row{{ $errors->has('email')? ' has-error': ''}}">
    {!! Form::label('email', 'Alamat Email', ['class'=>'text-md-right col-label col-md-4']) !!}
    <div class="col-md-4">
        {!! Form::text('email', null, ['class'=>'form-control']) !!}
        {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
    </div>
</div>
@if(Laratrust::hasRole('admin'))
<div class="form-group row{{ $errors->has('role')? ' has-error':''}}">
    {!! Form::label('role', 'Hak Akses', ['class'=>'text-md-right col-label col-md-4']) !!}
    <?php if(isset($role)) {
        $selected = $role;
    } else {
        $selected = 'null';
    }
    ?>
    <div class="col-md-4">
        {{ Form::select('role', [''=>'== Pilih ==']+$roles, $selected , ['class'=>'form-control']) }}
        {!! $errors->first('role', '<p class="help-block">:message</p>') !!}
    </div>
</div>
@endif

resources/views/user/_form-set-password.blade.php
<div class="form-group row{{ $errors->has('password') ?' has-error': ''}}">
    {!! Form::label('password', 'Password', ['class'=>'text-md-right col-label col-md-4']) !!}
    <div class="col-md-4">
        {!! Form::password('password', ['class'=>'form-control']) !!}
        {!! $errors->first('password', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group row">
    {!! Form::label('password-confirm', 'Re-Password', ['class'=>'text-md-right col-label col-md-4']) !!}
    <div class="col-md-4">
        {!! Form::password('password_confirmation', ['class'=>'form-control']) !!}
    </div>
</div>

resources/views/user/_form-user.blade.php
<div class="form-group row{{ $errors->has('name') ? ' has-error': ''}}">
    {!! Form::label('name', 'Nama', ['class'=>'text-md-right col-form-label col-md-4'])!!}
    <div class="col-md-4">
        {!! Form::text('name', null, ['class'=>'form-control']) !!}
        {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group row{{ $errors->has('username')? ' has-error': ''}}">
    {!! Form::label('username', 'User Name', ['class'=>'text-md-right col-label col-md-4']) !!}
    <div class="col-md-4">
        {!! Form::text('username', null, ['class'=>'form-control']) !!}
        {!! $errors->first('username', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group row{{ $errors->has('email')? ' has-error': ''}}">
    {!! Form::label('email', 'Alamat Email', ['class'=>'text-md-right col-label col-md-4']) !!}
    <div class="col-md-4">
        {!! Form::text('email', null, ['class'=>'form-control']) !!}
        {!! $errors->first('email', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group row{{ $errors->has('password') ?' has-error': ''}}">
    {!! Form::label('password', 'Password', ['class'=>'text-md-right col-label col-md-4']) !!}
    <div class="col-md-4">
        {!! Form::password('password', ['class'=>'form-control']) !!}
        {!! $errors->first('password', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group row">
    {!! Form::label('password-confirm', 'Re-Password', ['class'=>'text-md-right col-label col-md-4']) !!}
    <div class="col-md-4">
        {!! Form::password('password_confirmation', ['class'=>'form-control']) !!}
    </div>
</div>
<div class="form-group row{{ $errors->has('role')? ' has-error':''}}">
    {!! Form::label('role', 'Hak Akses', ['class'=>'text-md-right col-label col-md-4']) !!}
    <?php if(isset($role)) {
        $selected = $role;
    } else {
        $selected = 'null';
    }
    ?>
    <div class="col-md-4">
        {{ Form::select('role', [''=>'== Pilih ==']+$roles, $selected , ['class'=>'form-control']) }}
        {!! $errors->first('role', '<p class="help-block">:message</p>') !!}
    </div>
</div>

resources/views/user/edit-user.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <p>Informasi User</p>
                            {!! Form::model($user, ['url'=> route('user.update', $user->id), 'class'=>'form-horizontal', 'method'=>'put']) !!}
                                @include('user._form-edit-user')
                                <div class="form-group">
                                    <div class="col-md-4 offset-md-4">
                                        {!! Form::submit('Simpan', ['class'=>'btn btn-primary']) !!}
                                        <a href="{{ route('user.index') }}" class="btn btn-info">Batal</a>
                                    </div>
                                </div>
                            {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header d-flex p-0">
                    <div class="card-title p-3">Daftar Akun</div>
                    <ul class="nav nav-pills ml-auto p-2">
                        <li class="nav-item"><a class="nav-link active" href="{{route('user.create')}}">Tambah User</a></li>
                    </ul>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Nama</th>
                                    <th>Username</th>
                                    <th>Hak Akses</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if(isset($user))
                                <?php $i = $user->FirstItem(); ?>
                                @foreach($user as $usr)
                                    <tr>
                                        <td>{{ $i }}</td>
                                        <td>{{ $usr->name }}</td>
                                        <td>{{ $usr->username }}</td>
                                        <td>{{ $usr->roles()->first()->display_name }}</td>
                                        <td>
                                            @if(Auth::user()->name == $usr->name)
                                                {{ __('Status Sedang Login')}}
                                            @else
                                            <a href="{{ route('setpassword', $usr->id) }}"class="btn-warning btn-sm">Ganti Password</a>
                                            <a href="{{ route('user.edit', $usr->id) }}"class="btn-info btn-sm">Edit</a>
                                            <a href="#"class="btn-danger btn-sm" onclick="var check=confirm('Yakin Hapus {{ $usr->name }}'); if(check) {event.preventDefault();document.getElementById('formdeleteuser{{ $usr->id }}').submit();}">Hapus</a>
                                            {{ Form::open(['url'=>route('user.destroy', $usr->id), 'method'=>'delete', 'style'=>'display:none;', 'id'=>'formdeleteuser'.$usr->id])}}
                                            {{ Form::close() }}
                                            @endif
                                        </td>
                                    </tr>
                                    <?php $i++; ?>
                                @endforeach
                                @else
                                    <tr> Data Kosong </tr>
                                @endif
                            </body>
                        </table>
                    </div>
                    <div class="float-left pagination-md mb-0 clear-fix">
                            Menampilkan {{ $user->FirstItem() }} sampai {{$user->LastItem()}} Dari {{$user->total()}} Entri
                    </div>
                    <div class="float-right pagination-md mb-0 clear-fix">
                            {{$user->links()}}
                    </div>
                </div>
                <div class="overlay preload">
                    <i class="fa fa-refresh fa-spin"></i>
                </div>
            <div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function () {
            $('.preload').fadeOut();
        });
    </script>
@endsection

resources/views/user/new-user.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <p>Form New User</p>
                            {!! Form::open(['url'=> route('user.store')]) !!}
                                @include('user._form-user')
                                <div class="form-group row">
                                    <div class="col-md-4 offset-md-4">
                                        {!! Form::submit('Simpan', ['class'=>'btn btn-primary']) !!}
                                        <a href="{{ route('user.index') }}" class="btn btn-info">Kembali</a>
                                    </div>
                                </div>
                            {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/set-password.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <p>Ganti Password User</p>
                            {!! Form::model($user, ['url'=> route('updatepassword', $user->id), 'class'=>'form-horizontal', 'method'=>'put']) !!}
                                @include('user._form-set-password')
                                <div class="form-group">
                                    <div class="col-md-4 offset-md-4">
                                        {!! Form::submit('Simpan', ['class'=>'btn btn-primary']) !!}
                                        <a href="{{ route('user.index') }}" class="btn btn-info">Batal</a>
                                    </div>
                                </div>
                            {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/show-user.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 col-md-offset-2">
                <div class="card">
                    <div class="card-header">
                        <a href="{{ route('user.index') }}">Daftar Akun</a> > Informasi User 
                    </div>
                    <div class="card-body">
                        <p>Informasi User</p>
                            {!! Form::model($user, ['url'=> route('user.update', $user->id),'method'=>'put']) !!}
                                @include('user._form-user')
                                <div class="form-group">
                                    <div class="col-md-4 offset-md-4">
                                        {!! Form::submit('Simpan', ['type'=>'button','class'=>'btn btn-primary']) !!}
                                    </div>
                                </div>
                            {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection